---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    port.authrpc: "8551"
    service: rollup-boost
  labels:
    l2.service: rollup-boost
  name: rollup-boost
spec:
  replicas: 1
  selector:
    matchLabels:
      l2.service: rollup-boost
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        port.authrpc: "8551"
        service: rollup-boost
      labels:
        l2.service: rollup-boost
    spec:
      containers:
        - args:
            - --rpc-host
            - 0.0.0.0
            - --rpc-port
            - "8551"
            - --l2-jwt-path
            - /data/jwtsecret
            - --l2-url
            - http://op-geth:8551
            - --builder-jwt-path
            - /data/jwtsecret
            - --builder-url
            - http://op-rbuilder:8551
            - --guarantor-jwt-path
            - /data/jwtsecret
            - --guarantor-url
            - http://tx-order-guarantor:1545
          image: docker.io/cbarbieru/rollup-boost:0.1
          name: rollup-boost
          ports:
            - containerPort: 8551
              protocol: TCP
          volumeMounts:
            - mountPath: /data/jwtsecret
              name: rollup-boost-jwtsecret
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/sceal/storage/jwtsecret
            type: File
          name: rollup-boost-jwtsecret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    port.authrpc: "8551"
    port.http: "8545"
    port.metrics: "9090"
    port.rpc: "30303"
    service: op-rbuilder
  labels:
    l2.service: op-rbuilder
  name: op-rbuilder
spec:
  replicas: 1
  selector:
    matchLabels:
      l2.service: op-rbuilder
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        port.authrpc: "8551"
        port.http: "8545"
        port.metrics: "9090"
        port.rpc: "30303"
        service: op-rbuilder
      labels:
        l2.service: op-rbuilder
    spec:
      containers:
        - args:
            - node
            - --authrpc.port
            - "8551"
            - --authrpc.addr
            - 0.0.0.0
            - --authrpc.jwtsecret
            - /data/jwtsecret
            - --http
            - --http.addr
            - 0.0.0.0
            - --http.port
            - "8545"
            - --chain
            - /data/l2-genesis.json
            - --datadir
            - /data_op_reth
            - --disable-discovery
            - --color
            - never
            - --metrics
            - 0.0.0.0:9090
            - --port
            - "30303"
            - --builder.enable-revert-protection
            - --trusted-peers
            - enode://79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8@op-geth:30303
          image: docker.io/cbarbieru/op-rbuilder:sha-4f1931b-cb
          name: op-rbuilder
          ports:
            - containerPort: 8551
              protocol: TCP
            - containerPort: 8545
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
            - containerPort: 30303
              protocol: TCP
          volumeMounts:
            - mountPath: /data/jwtsecret
              name: op-rbuilder-jwtsecret
            - mountPath: /data/l2-genesis.json
              name: op-rbuilder-l2-genesis
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/sceal/storage/jwtsecret
          name: op-rbuilder-jwtsecret
        - hostPath:
            path: /mnt/sceal/storage/l2-genesis.json
            type: File
          name: op-rbuilder-l2-genesis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    port.http: "1545"
    service: tx-order-guarantor
  name: tx-order-guarantor
  labels:
    l2.service: tx-order-guarantor
spec:
  replicas: 1
  selector:
    matchLabels:
      l2.service: tx-order-guarantor
  template:
    metadata:
      labels:
        l2.service: tx-order-guarantor
    spec:
      runtimeClassName: kata-qemu-tdx
      containers:
        - name: tx-order-guarantor
          image: docker.io/cbarbieru/tx-order-guarantor:0.1
          ports:
            - containerPort: 1545

---
apiVersion: v1
kind: Service
metadata:
  name: tx-order-guarantor
spec:
  selector:
    l2.service: tx-order-guarantor
  ports:
    - protocol: TCP
      port: 1545
      targetPort: 1545
status:
  loadBalancer: {}

