---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /mnt/sceal/storage/docker-compose.yaml --volumes hostPath -o /home/cbarbieru/bp-k8s-2/02_opstack_rollup_boost.yaml
    kompose.version: 1.31.0 (a04ecdb9e)
    playground: "true"
    playground.session: 5c090b8d-ad86-4a1b-8562-eccb07e962de
    port.authrpc: "8551"
    port.http: "8545"
    port.metrics: "9090"
    port.rpc: "30303"
    service: op-rbuilder
  creationTimestamp: null
  labels:
    io.kompose.service: op-rbuilder
  name: op-rbuilder
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: op-rbuilder
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /mnt/sceal/storage/docker-compose.yaml --volumes hostPath -o /home/cbarbieru/bp-k8s-2/02_opstack_rollup_boost.yaml
        kompose.version: 1.31.0 (a04ecdb9e)
        playground: "true"
        playground.session: 5c090b8d-ad86-4a1b-8562-eccb07e962de
        port.authrpc: "8551"
        port.http: "8545"
        port.metrics: "9090"
        port.rpc: "30303"
        service: op-rbuilder
      creationTimestamp: null
      labels:
        io.kompose.network/ethplayground: "true"
        io.kompose.service: op-rbuilder
    spec:
      containers:
        - args:
            - node
            - --authrpc.port
            - "8551"
            - --authrpc.addr
            - 0.0.0.0
            - --authrpc.jwtsecret
            - /data/jwtsecret
            - --http
            - --http.addr
            - 0.0.0.0
            - --http.port
            - "8545"
            - --chain
            - /data/l2-genesis.json
            - --datadir
            - /data_op_reth
            - --disable-discovery
            - --color
            - never
            - --metrics
            - 0.0.0.0:9090
            - --port
            - "30303"
            - --builder.enable-revert-protection
            - --trusted-peers
            - enode://79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8@op-geth:30303
          image: docker.io/cbarbieru/op-rbuilder:sha-4f1931b-cb
          name: op-rbuilder
          ports:
            - containerPort: 8551
              protocol: TCP
            - containerPort: 8545
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
            - containerPort: 30303
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: data
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/sceal/storage
          name: data
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    port.http: "8545"
    service: tx-order-guarantor
  name: tx-order-guarantor
  labels:
    app: tx-order-guarantor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tx-order-guarantor
  template:
    metadata:
      labels:
        io.kompose.service: tx-order-guarantor
    spec:
      # runtimeClassName: enclave-cc
      containers:
        - name: tx-order-guarantor
          image: docker.io/cbarbieru/tx-order-guarantor:0.1
          ports:
            - containerPort: 8545

---
apiVersion: v1
kind: Service
metadata:
  name: tx-order-guarantor
spec:
  selector:
    io.kompose.service: tx-order-guarantor
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545
status:
  loadBalancer: {}

