apiVersion: v1
kind: Service
metadata:
  annotations:
    service: beacon
  labels:
    l1.service: beacon
  name: beacon
spec:
  ports:
    - name: "udp-9000"
      port: 9000
      protocol: UDP
      targetPort: 9000
    - name: "tcp-9000"
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: "9100"
      port: 9100
      targetPort: 9100
    - name: "3500"
      port: 3500
      targetPort: 3500
  selector:
    l1.service: beacon