apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath -o /Users/claudiu/Projects/SCEAL/builder-playground-opstack-k8s/resources
    kompose.version: 1.36.0 (HEAD)
    playground: "true"
    playground.session: 39ad23af-81d3-4605-bec9-a4ea81b1a3b8
    port.http: "3500"
    port.p2p: "9000"
    port.quic-p2p: "9100"
    service: beacon
  labels:
    io.kompose.service: beacon
  name: beacon
spec:
  ports:
    - name: "9000"
      port: 9000
      protocol: UDP
      targetPort: 9000
    - name: "9001"
      port: 9001
      targetPort: 9000
    - name: "9100"
      port: 9100
      targetPort: 9100
    - name: "3500"
      port: 3500
      targetPort: 3500
  selector:
    io.kompose.service: beacon
