apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath -o /Users/claudiu/Projects/SCEAL/builder-playground-opstack-k8s/resources
    kompose.version: 1.36.0 (HEAD)
    playground: "true"
    playground.session: 39ad23af-81d3-4605-bec9-a4ea81b1a3b8
    port.http: "3500"
    port.p2p: "9000"
    port.quic-p2p: "9100"
    service: beacon
  labels:
    io.kompose.service: beacon
  name: beacon
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: beacon
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath -o /Users/claudiu/Projects/SCEAL/builder-playground-opstack-k8s/resources
        kompose.version: 1.36.0 (HEAD)
        playground: "true"
        playground.session: 39ad23af-81d3-4605-bec9-a4ea81b1a3b8
        port.http: "3500"
        port.p2p: "9000"
        port.quic-p2p: "9100"
        service: beacon
      labels:
        io.kompose.service: beacon
    spec:
      containers:
        - args:
            - bn
            - --datadir
            - /data_beacon
            - --testnet-dir
            - /data/testnet-dir
            - --enable-private-discovery
            - --disable-peer-scoring
            - --staking
            - --enr-address
            - 127.0.0.1
            - --enr-udp-port
            - "9000"
            - --enr-tcp-port
            - "9000"
            - --enr-quic-port
            - "9100"
            - --port
            - "9000"
            - --quic-port
            - "9100"
            - --http
            - --http-port
            - "3500"
            - --http-address
            - 0.0.0.0
            - --http-allow-origin
            - '*'
            - --disable-packet-filter
            - --target-peers
            - "0"
            - --execution-endpoint
            - http://el:8551
            - --execution-jwt
            - /data/jwtsecret
            - --always-prepare-payload
            - --prepare-payload-lookahead
            - "8000"
            - --suggested-fee-recipient
            - 0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990
          command:
            - lighthouse
          image: sigp/lighthouse:v7.0.0-beta.0
          livenessProbe:
            exec:
              command:
                - chmod +x /artifacts/scripts/query.sh && /artifacts/scripts/query.sh http://localhost:3500/eth/v1/node/syncing
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 30
          name: beacon
          ports:
            - containerPort: 9000
              protocol: UDP
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9100
              protocol: TCP
            - containerPort: 3500
              protocol: TCP
          volumeMounts:
            - mountPath: /data/jwtsecret
              name: beacon-hostpath0
            - mountPath: /data/testnet-dir
              name: beacon-hostpath3
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/sceal/storage/jwtsecret
          name: beacon-hostpath0
        - hostPath:
            path: /mnt/sceal/storage/testnet
          name: beacon-hostpath3
