apiVersion: v1
kind: ConfigMap
metadata:
  name: contender-scenario
data:
  stress.toml: |
    [runtime]
    tx_count = 100
    concurrent_sends = 10
    gas_price = "1gwei"

    [transaction]
    to = "0x0000000000000000000000000000000000000000"
    value = "0.1ether"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contender-script
data:
  run.sh: |
    #!/bin/sh

    PREFUNDED_PRIV_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    PREFUNDED_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266

    ROLLUP_RPC=http://rollup-boost.default.svc.cluster.local:8551
    BUILDER_RPC=http://op-rbuilder.default.svc.cluster.local:8551

    echo "Using prefunded address: $PREFUNDED_ADDRESS"

    echo "Running contender setup..."
    contender setup \
      -p $PREFUNDED_PRIV_KEY \
      /data/scenario/stress.toml \
      -r $ROLLUP_RPC \
      --optimism

    echo "Running fill-block spam workload..."
    contender spam \
      --tpb 50 \
      -d 10 \
      --min-balance 0.2eth \
      -p $PREFUNDED_PRIV_KEY \
      --auth $BUILDER_RPC \
      --jwt /data/jwtsecret \
      --optimism fill-block
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contender
  labels:
    app: contender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contender
  template:
    metadata:
      labels:
        app: contender
    spec:
      containers:
        - name: contender
          image: flashbots/contender:latest
          command: ["/bin/sh", "-c"]
          args: ["sleep infinity"]
          volumeMounts:
            - name: contender-data
              mountPath: /root/.contender
            - name: scenario-config
              mountPath: /data/scenario
            - name: script-config
              mountPath: /script
            - name: jwt-secret
              mountPath: /data/jwtsecret
      volumes:
        - name: contender-data
          emptyDir: {}
        - name: scenario-config
          configMap:
            name: contender-scenario
        - name: script-config
          configMap:
            name: contender-script
            defaultMode: 0755
        - name: jwt-secret
          hostPath:
              path: /mnt/sceal/storage/jwtsecret

