apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    service: el
  labels:
    l1.service: el
  name: el
spec:
  replicas: 1
  selector:
    matchLabels:
      l1.service: el
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        service: el
      labels:
        l1.service: el
    spec:
      containers:
        - name: el
          image: ghcr.io/paradigmxyz/reth:v1.4.8
          command:
            - /usr/local/bin/reth
          args:
            - node
            - --chain
            - /data/genesis.json
            - --datadir
            - /data_reth
            - --color
            - never
            - --ipcpath
            - /data_reth/reth.ipc
            - --addr
            - 127.0.0.1
            - --port
            - "30303"
            - --http
            - --http.addr
            - 0.0.0.0
            - --http.api
            - admin,eth,web3,net,rpc,mev,flashbots
            - --http.port
            - "8545"
            - --ws
            - --ws.addr
            - 0.0.0.0
            - --ws.port
            - "8546"
            - --ws.api
            - eth,web3,net,txpool,debug,trace
            - --ws.origins
            - '*'
            - --authrpc.port
            - "8551"
            - --authrpc.addr
            - 0.0.0.0
            - --authrpc.jwtsecret
            - /data/jwtsecret
            - --metrics
            - 0.0.0.0:9090
            - --engine.persistence-threshold
            - "0"
            - --engine.memory-block-buffer-target
            - "0"
            - -vvv
          ports:
            - containerPort: 30303
            - containerPort: 8545
            - containerPort: 8546
            - containerPort: 8551
            - containerPort: 9090
          volumeMounts:
              - mountPath: /data/genesis.json
                name: el-genesis
              - mountPath: /data/jwtsecret
                name: el-jwtsecret
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/sceal/storage/genesis.json
            type: File
          name: el-genesis
        - hostPath:
            path: /mnt/sceal/storage/jwtsecret
            type: File
          name: el-jwtsecret