apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath -o /Users/claudiu/Projects/SCEAL/builder-playground-opstack-k8s/resources
    kompose.version: 1.36.0 (HEAD)
    playground: "true"
    playground.session: 39ad23af-81d3-4605-bec9-a4ea81b1a3b8
    port.authrpc: "8551"
    port.http: "8545"
    port.metrics: "9090"
    port.rpc: "30303"
    service: el
  labels:
    io.kompose.service: el
  name: el
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: el
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath -o /Users/claudiu/Projects/SCEAL/builder-playground-opstack-k8s/resources
        kompose.version: 1.36.0 (HEAD)
        playground: "true"
        playground.session: 39ad23af-81d3-4605-bec9-a4ea81b1a3b8
        port.authrpc: "8551"
        port.http: "8545"
        port.metrics: "9090"
        port.rpc: "30303"
        service: el
      labels:
        io.kompose.service: el
    spec:
      containers:
        - args:
            - node
            - --chain
            - /data/genesis.json
            - --datadir
            - /data_reth
            - --color
            - never
            - --ipcpath
            - /data_reth/reth.ipc
            - --addr
            - 127.0.0.1
            - --port
            - "30303"
            - --http
            - --http.addr
            - 0.0.0.0
            - --http.api
            - admin,eth,web3,net,rpc,mev,flashbots
            - --http.port
            - "8545"
            - --authrpc.port
            - "8551"
            - --authrpc.addr
            - 0.0.0.0
            - --authrpc.jwtsecret
            - /data/jwtsecret
            - --metrics
            - 0.0.0.0:9090
            - --engine.persistence-threshold
            - "0"
            - --engine.memory-block-buffer-target
            - "0"
            - -vvv
          command:
            - /usr/local/bin/reth
          image: ghcr.io/paradigmxyz/reth:v1.3.1
          name: el
          ports:
            - containerPort: 30303
              protocol: TCP
            - containerPort: 8545
              protocol: TCP
            - containerPort: 8551
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /data/genesis.json
              name: el-hostpath1
            - mountPath: /data/jwtsecret
              name: el-hostpath2
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/sceal/storage/genesis.json
            type: File
          name: el-hostpath1
        - hostPath:
            path: /mnt/sceal/storage/jwtsecret
            type: File
          name: el-hostpath2
