apiVersion: v1
kind: Service
metadata:
  labels:
    l1.service: el
  name: el
spec:
  ports:
    - name: "30303"
      port: 30303
      targetPort: 30303
    - name: "8545"
      port: 8545
      targetPort: 8545
    - name: "8546"
      port: 8546
      targetPort: 8546
    - name: "8551"
      port: 8551
      targetPort: 8551
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    l1.service: el