apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    service: op-batcher
  labels:
    l2.service: op-batcher
  name: op-batcher
spec:
  replicas: 1
  selector:
    matchLabels:
      l2.service: op-batcher
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        service: op-batcher
      labels:
        l2.service: op-batcher
    spec:
      containers:
        - args:
            - --l1-eth-rpc
            - http://el:8545
            - --l2-eth-rpc
            - http://op-geth:8545
            - --rollup-rpc
            - http://op-node:8549
            - --max-channel-duration=2
            - --sub-safety-margin=4
            - --poll-interval=1s
            - --num-confirmations=1
            - --private-key=0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6
          command:
            - op-batcher
          image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher:v1.12.0-rc.1
          name: op-batcher
      restartPolicy: Always
