apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath -o /Users/claudiu/Projects/SCEAL/builder-playground-opstack-k8s/resources
    kompose.version: 1.36.0 (HEAD)
    playground: "true"
    playground.session: 39ad23af-81d3-4605-bec9-a4ea81b1a3b8
    port.authrpc: "8551"
    port.http: "8545"
    port.metrics: "6061"
    port.rpc: "30303"
    port.ws: "8546"
    service: op-geth
  labels:
    io.kompose.service: op-geth
  name: op-geth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: op-geth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath -o /Users/claudiu/Projects/SCEAL/builder-playground-opstack-k8s/resources
        kompose.version: 1.36.0 (HEAD)
        playground: "true"
        playground.session: 39ad23af-81d3-4605-bec9-a4ea81b1a3b8
        port.authrpc: "8551"
        port.http: "8545"
        port.metrics: "6061"
        port.rpc: "30303"
        port.ws: "8546"
        service: op-geth
      labels:
        io.kompose.service: op-geth
    spec:
      containers:
        - args:
            - -c
            - geth init --datadir /data_opgeth --state.scheme hash /data/l2-genesis.json && exec geth --datadir /data_opgeth --verbosity 3 --http --http.corsdomain "*" --http.vhosts "*" --http.addr 0.0.0.0 --http.port 8545 --http.api web3,debug,eth,txpool,net,engine,miner --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --ws.api debug,eth,txpool,net,engine,miner --syncmode full --nodiscover --maxpeers 5 --rpc.allow-unprotected-txs --authrpc.addr 0.0.0.0 --authrpc.port 8551 --authrpc.vhosts "*" --authrpc.jwtsecret /data/jwtsecret --gcmode archive --state.scheme hash --port 30303 --nodekey /data/enode-key-1.txt --metrics --metrics.addr 0.0.0.0 --metrics.port 6061
          command:
            - /bin/sh
          image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101503.2-rc.5
          name: op-geth
          ports:
            - containerPort: 8545
              protocol: TCP
            - containerPort: 8546
              protocol: TCP
            - containerPort: 8551
              protocol: TCP
            - containerPort: 30303
              protocol: TCP
            - containerPort: 6061
              protocol: TCP
          volumeMounts:
            - mountPath: /data/l2-genesis.json
              name: op-geth-hostpath1
            - mountPath: /data/jwtsecret
              name: op-geth-hostpath2
            - mountPath: /data/enode-key-1.txt
              name: op-geth-hostpath3
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/sceal/storage/l2-genesis.json
            type: File
          name: op-geth-hostpath1
        - hostPath:
            path: /mnt/sceal/storage/jwtsecret
            type: File
          name: op-geth-hostpath2
        - hostPath:
            path: /mnt/sceal/storage/enode-key-1.txt
            type: File
          name: op-geth-hostpath3
