apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f /Users/claudiu/.playground/devnet/docker-compose.yaml convert
    kompose.version: 1.36.0 (HEAD)
    playground: "true"
    playground.session: 39ad23af-81d3-4605-bec9-a4ea81b1a3b8
    port.authrpc: "8551"
    port.http: "8545"
    port.metrics: "6061"
    port.rpc: "30303"
    port.ws: "8546"
    service: op-geth
  labels:
    io.kompose.service: op-geth
  name: op-geth
spec:
  ports:
    - name: "8546"
      port: 8546
      targetPort: 8545
    - name: "8547"
      port: 8547
      targetPort: 8546
    - name: "8552"
      port: 8552
      targetPort: 8551
    - name: "30304"
      port: 30304
      targetPort: 30303
    - name: "6061"
      port: 6061
      targetPort: 6061
  selector:
    io.kompose.service: op-geth
