apiVersion: v1
kind: Service
metadata:
  annotations:
    port.http: "8549"
    port.metrics: "7300"
    port.p2p: "9003"
    service: op-node
  labels:
    l2.service: op-node
  name: op-node
spec:
  ports:
    - name: "8549"
      port: 8549
      targetPort: 8549
    - name: "tcp-9003"
      port: 9003
      protocol: TCP
      targetPort: 9003
    - name: "udp-9003"
      port: 9003
      protocol: UDP
      targetPort: 9003
    - name: "7300"
      port: 7300
      targetPort: 7300
  selector:
    l2.service: op-node
