apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath -o /Users/claudiu/Projects/SCEAL/builder-playground-opstack-k8s/resources
    kompose.version: 1.36.0 (HEAD)
    playground: "true"
    playground.session: 39ad23af-81d3-4605-bec9-a4ea81b1a3b8
    port.authrpc: "8551"
    port.http: "8545"
    port.metrics: "9090"
    port.rpc: "30303"
    service: op-rbuilder
  labels:
    io.kompose.service: op-rbuilder
  name: op-rbuilder
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: op-rbuilder
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath -o /Users/claudiu/Projects/SCEAL/builder-playground-opstack-k8s/resources
        kompose.version: 1.36.0 (HEAD)
        playground: "true"
        playground.session: 39ad23af-81d3-4605-bec9-a4ea81b1a3b8
        port.authrpc: "8551"
        port.http: "8545"
        port.metrics: "9090"
        port.rpc: "30303"
        service: op-rbuilder
      labels:
        io.kompose.service: op-rbuilder
    spec:
      runtimeClassName: kata-qemu-tdx
      containers:
        - args:
            - node
            - --authrpc.port
            - "8551"
            - --authrpc.addr
            - 0.0.0.0
            - --authrpc.jwtsecret
            - /data/jwtsecret
            - --http
            - --http.addr
            - 0.0.0.0
            - --http.port
            - "8545"
            - --chain
            - /data/l2-genesis.json
            - --datadir
            - /data_op_reth
            - --disable-discovery
            - --color
            - never
            - --metrics
            - 0.0.0.0:9090
            - --port
            - "30303"
            - --builder.enable-revert-protection
            - --trusted-peers
            - enode://79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8@op-geth:30303
          image: ghcr.io/flashbots/op-rbuilder:sha-4f1931b
          name: op-rbuilder
          ports:
            - containerPort: 8551
              protocol: TCP
            - containerPort: 8545
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
            - containerPort: 30303
              protocol: TCP
          volumeMounts:
            - mountPath: /data/jwtsecret
              name: op-rbuilder-hostpath1
            - mountPath: /data/l2-genesis.json
              name: op-rbuilder-hostpath2
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/sceal/storage/jwtsecret
          name: op-rbuilder-hostpath1
        - hostPath:
            path: /mnt/sceal/storage/l2-genesis.json
          name: op-rbuilder-hostpath2
