apiVersion: v1
kind: Service
metadata:
  annotations:
    port.authrpc: "8551"
    service: rollup-boost
  labels:
    l2.service: rollup-boost
  name: rollup-boost
spec:
  ports:
    - name: "8551"
      port: 8551
      targetPort: 8551
  selector:
    l2.service: rollup-boost
