apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f /Users/claudiu/.playground/devnet/docker-compose.yaml convert
    kompose.version: 1.36.0 (HEAD)
    playground: "true"
    playground.session: 39ad23af-81d3-4605-bec9-a4ea81b1a3b8
    port.authrpc: "8551"
    service: rollup-boost
  labels:
    io.kompose.service: rollup-boost
  name: rollup-boost
spec:
  ports:
    - name: "8554"
      port: 8554
      targetPort: 8551
  selector:
    io.kompose.service: rollup-boost
