apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    service: validator
  labels:
    l1.service: validator
  name: validator
spec:
  replicas: 1
  selector:
    matchLabels: 
      l1.service: validator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        service: validator
      labels:
        l1.service: validator
    spec:
      containers:
        - name: validator
          image: 
            sigp/lighthouse:v7.0.0-beta.0
          command:
            - lighthouse
          args:
            - vc
            - --datadir
            - /data/validator
            - --testnet-dir
            - /data/testnet-dir
            - --init-slashing-protection
            - --beacon-nodes
            - http://beacon:3500
            - --suggested-fee-recipient
            - 0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990
            - --builder-proposals
            - --prefer-builder-proposals
          volumeMounts:
            - mountPath: /data/testnet-dir
              name: validator-testnet
            - mountPath: /data/validator
              name: validator-secrets
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/sceal/storage/testnet
          name: validator-testnet
        - hostPath:
            path: /mnt/sceal/storage/data_validator
          name: validator-secrets